name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

    # Use a local bundle path so caching vendor/bundle works across Ruby versions
    - run: bundle config set path vendor/bundle
    - run: bundle config set deployment 'true'
    - run: bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build
